# Generated by Django 3.2.9 on 2022-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20211209_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
